version: "2.11.2"

services:
  core:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      SECRET_TOKEN: ${SECRET_TOKEN}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_SERVER: kafkahost:9092
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    extra_hosts:
      kafkahost: ${KAFKA_HOST}
    networks:
      - dsp

networks:
  dsp:
    name: dsp
    external: true
